### ISSUE TITLE
Problem with CSS

### ISSUE THREAD

**Issue by vbauer** [0legg/AndroidSDKSafariExtension#1]
![screen shot 2015-07-20 at 05 02 16](https://cloud.githubusercontent.com/assets/578021/8768299/35285e18-2e94-11e5-91c3-0c35fb4e3733.png)

**Comment by 0legg** [comment]
Fixed in https://github.com/0legg/AndroidSDKSafariExtension/commit/990de987d3ad92c5ccda0dc50fdc0524ce5fbf09

**Comment by vbauer** [comment]
Thanks!
